# meedan/elasticsearch
# elasticsearch 5.2 with elasticsearch-gui plugin

FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.2
# FROM elasticsearch:5.2
MAINTAINER sysops@meedan.com

RUN elasticsearch-plugin install analysis-icu 
